#!/bin/sh

function start() {
    echo "\n// Autogenerated file, DO NOT EDIT.\n" > tklist.h
    echo "typedef enum TokenKind {" >> tklist.h
    echo "static const char* const tkrepr[] = {" > tkrepr.h
    echo "static const char* const tksrepr[] = {" > tksrepr.h
}

function finish() {
    echo "};\n" >> tkrepr.h
    echo "};\n" >> tksrepr.h
    echo "} TokenKind;\n" >> tklist.h
    cat tklist.h tkrepr.h tksrepr.h > TokenKindDefs.h
    rm tklist.h tkrepr.h tksrepr.h
}

function add() {
    repr=${2}
    srepr=${3:-$2}
    echo "    $1," >> tklist.h
    echo "    [$1] = \"$srepr\"," >> tksrepr.h
    echo "    [$1] = \"$repr\"," >> tkrepr.h
}

start
add TKNullChar "EOF"
add TKKeyword_cheater "cheater"
add TKKeyword_for "for"  "for "
add TKKeyword_while "while"  "while "
add TKKeyword_if "if" "if "
add TKKeyword_end "end"
add TKKeyword_function "function"
add TKKeyword_declare "declare"
add TKKeyword_test "test"  "test "
add TKKeyword_check "check"  "check "
add TKKeyword_not "not "
add TKKeyword_and " and "
add TKKeyword_or " or "
add TKKeyword_in " in "
add TKKeyword_do " do "
add TKKeyword_then " then "
add TKKeyword_as " as "
add TKKeyword_else "else "
add TKKeyword_type "type "
add TKKeyword_return "return "
add TKKeyword_returns " returns "
add TKKeyword_extends " extends "
add TKKeyword_var "var "
add TKKeyword_let "let "
add TKKeyword_import "import "
add TKIdentifier "(id)"
add TKFunctionCall "(call)"
add TKSubscript "(sub)"
add TKNumber "'123'"
add TKIdentifierResolved "[id]"
add TKFunctionCallResolved "[call]"
add TKSubscriptResolved "[sub]"
add TKNumberAsInt "123"
add TKNumberAsDbl "1.23"
add TKNumberAsUInt "+123"
add TKMultiDotNumber "1.2.3"
add TKSpaces "(spc)"
add TKOneSpace "(sp1)"
add TKTab "(tab)"
add TKNewline "(nl)"
add TKLineComment "(cmt)"
add TKAlphabet "a"
add TKAmpersand "&"
add TKArrayClose "]"
add TKArrayOpen "["
add TKArrayDims "[:]"
add TKAt "@"
add TKBraceClose "}"
add TKBraceOpen "{"
add TKDigit "1"
add TKHash "#"
add TKExclamation "!"
add TKPipe "|"
add TKOpAssign " = " "="
add TKVarAssign "v=" "v="
add TKOpEQ " == " "=="
add TKOpNE " != " "!="
add TKOpGE " >= " ">="
add TKOpGT " > " ">"
add TKOpLE " <= " "<="
add TKOpLT " < " "<"
add TKOpMod " % " "%"
add TKOpModEq " %= "
add TKOpResults " -> "
add TKOpNotResults " -/> "
add TKParenClose ")"
add TKParenOpen "("
add TKPeriod "."
add TKOpComma ", "
add TKOpSemiColon "; "
add TKOpColon ":"
add TKStringBoundary "\\\""
add TKString "\\\"abc\\\""
add TKRegexBoundary "'"
add TKRegex "'abc'"
add TKInlineBoundary "\`"
add TKInline "\`abc\`"
add TKUnderscore "_"
add TKSlash " / " "/"
add TKBackslash " \\\\\\ " "\\\\\\"
add TKPlus " + " "+"
add TKMinus " - " "-"
add TKUnaryMinus " -" "-"
add TKTimes " * " "*"
add TKPower "^"
add TKPowerEq " ^= "
add TKTilde "~"
add TKDollar "$"
add TKUnits "|N.m/s"
add TKUnknown "(unk)"
add TKPlusEq " += "
add TKMinusEq " -= "
add TKSlashEq " /= "
add TKTimesEq " *= "
add TKColEq " := "
add TKQuestion "?"
finish
