#!/bin/sh
if [ "$1" == "d" ]
then
    DIAG="d"
    FILE=$2
else
    DIAG=
    FILE=$1
fi

[ -f "$FILE" ] || exit 6
TGT=${FILE%%.ch}$EXTN.bin
printf "  ...\r" 1>&2
make -s DIAG=$DIAG -f Makerunner $TGT && [ -f $TGT ] && ./$TGT $*

